spring.application.name=ms-orders
server.port=8080

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# Security login
spring.security.user.name=admin
spring.security.user.password=admin

# oauth2 resource server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/f9bce5c0-eb96-4341-aad7-411ae980b12a/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=

# Microservices
catalog.service.url=${MS_CATALOG}