spring.application.name=ms-orders
server.port=${SERVER_PORT:8081}

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/orders_db?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME:myuser}
spring.datasource.password=${DB_PASSWORD:secret}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.mvc.problemdetails.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.docker.compose.enabled=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=${ENTRA_ISSUER:https://login.microsoftonline.com/f9bce5c0-eb96-4341-aad7-411ae980b12a/v2.0}
spring.security.oauth2.resourceserver.jwt.audiences=${ENTRA_AUDIENCE:15f9fdcd-344e-4a9b-931c-9980f055b722}
catalog.service.url=${MS_CATALOG:http://localhost:8080}
